name: test_github_actions
on:
  push:
    branches:
    - main
jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Welcome message
    - run: echo "Hello this is the first job in Github Actions!"
    
    - name: Clone the repository
      uses: actions/checkout@v6.0.1
    - name: List all Project files
    - run: ls -la
